import type { SessionPayload } from "./index";

export const SAMPLE_SESSION: SessionPayload = {
  id: "session-sample-vendor-bill",
  createdAt: "2026-09-19T16:00:00.000Z",
  title: "Enter a vendor bill in the demo ledger",
  startUrl: "https://demo.saucedemo.com/inventory.html",
  events: [
    {
      id: "evt-1",
      ts: 1,
      type: "navigate",
      url: "https://demo.saucedemo.com/",
      selector: "document",
      href: "https://demo.saucedemo.com/",
      title: "Swag Labs",
    },
    {
      id: "evt-2",
      ts: 2,
      type: "input",
      url: "https://demo.saucedemo.com/",
      selector: "#user-name",
      tagName: "INPUT",
      text: "Username",
      value: "standard_user",
    },
    {
      id: "evt-3",
      ts: 3,
      type: "input",
      url: "https://demo.saucedemo.com/",
      selector: "#password",
      tagName: "INPUT",
      text: "Password",
      value: "••••",
    },
    {
      id: "evt-4",
      ts: 4,
      type: "click",
      url: "https://demo.saucedemo.com/",
      selector: "#login-button",
      tagName: "INPUT",
      text: "Login",
    },
    {
      id: "evt-5",
      ts: 5,
      type: "click",
      url: "https://demo.saucedemo.com/inventory.html",
      selector: "#add-to-cart-sauce-labs-backpack",
      tagName: "BUTTON",
      text: "Add to cart",
    },
    {
      id: "evt-6",
      ts: 6,
      type: "click",
      url: "https://demo.saucedemo.com/inventory.html",
      selector: "a.shopping_cart_link",
      tagName: "A",
      text: "Cart",
    },
    {
      id: "evt-7",
      ts: 7,
      type: "click",
      url: "https://demo.saucedemo.com/cart.html",
      selector: "#checkout",
      tagName: "BUTTON",
      text: "Checkout",
    },
  ],
  steps: [],
};
