import type { SessionPayload } from "./index";

const INBOX = "https://mail.example/inbox";
const EHR = "https://demo.openemr.io/a/openemr";

/**
 * Seed skill: referral PDF in Mary's email → login EHR → four screens.
 * Inbox/login never hydrate at the same time as the four EHR forms.
 */
export const SAMPLE_SESSION: SessionPayload = {
  id: "session-sample-openemr-referral",
  createdAt: "2026-09-19T16:00:00.000Z",
  title: "Referral PDF in email → four EHR screens",
  startUrl: INBOX,
  events: [
    {
      id: "evt-01",
      ts: 1,
      type: "navigate",
      url: INBOX,
      selector: "document",
      href: INBOX,
      title: "Inbox",
    },
    {
      id: "evt-02",
      ts: 2,
      type: "click",
      url: INBOX,
      selector: "a.thread[data-subject='Referral']",
      tagName: "A",
      text: "Open referral email",
    },
    {
      id: "evt-03",
      ts: 3,
      type: "click",
      url: INBOX,
      selector: "a[href$='.pdf']",
      tagName: "A",
      text: "Open attached referral PDF",
      value: "referral-fax.pdf",
    },
    {
      id: "evt-04",
      ts: 4,
      type: "navigate",
      url: EHR,
      selector: "document",
      href: EHR,
      title: "OpenEMR — Sign in",
    },
    {
      id: "evt-05",
      ts: 5,
      type: "input",
      url: EHR,
      selector: "#authUser",
      tagName: "INPUT",
      text: "Username",
      value: "admin",
    },
    {
      id: "evt-06",
      ts: 6,
      type: "input",
      url: EHR,
      selector: "#clearPass",
      tagName: "INPUT",
      text: "Password",
      value: "••••",
    },
    {
      id: "evt-07",
      ts: 7,
      type: "submit",
      url: EHR,
      selector: "form#login",
      tagName: "FORM",
      text: "Log in",
    },
    {
      id: "evt-08",
      ts: 8,
      type: "click",
      url: EHR,
      selector: "a[href*='new_search']",
      tagName: "A",
      text: "Patient > New/Search",
    },
    {
      id: "evt-09",
      ts: 9,
      type: "input",
      url: EHR,
      selector: "input[name='form_fname']",
      tagName: "INPUT",
      text: "First name",
      value: "HACKDEMO-River",
    },
    {
      id: "evt-10",
      ts: 10,
      type: "input",
      url: EHR,
      selector: "input[name='form_lname']",
      tagName: "INPUT",
      text: "Last name",
      value: "HACKDEMO-Calder",
    },
    {
      id: "evt-11",
      ts: 11,
      type: "input",
      url: EHR,
      selector: "input[name='form_DOB']",
      tagName: "INPUT",
      text: "Date of birth",
      value: "1984-06-12",
    },
    {
      id: "evt-12",
      ts: 12,
      type: "change",
      url: EHR,
      selector: "select[name='form_sex']",
      tagName: "SELECT",
      text: "Sex",
      value: "Female",
    },
    {
      id: "evt-13",
      ts: 13,
      type: "click",
      url: EHR,
      selector: "button[name='form_create']",
      tagName: "BUTTON",
      text: "Create New Patient",
    },
    {
      id: "evt-14",
      ts: 14,
      type: "click",
      url: EHR,
      selector: "a[title='Appointments']",
      tagName: "A",
      text: "Appointments +",
    },
    {
      id: "evt-15",
      ts: 15,
      type: "change",
      url: EHR,
      selector: "select[name='form_category']",
      tagName: "SELECT",
      text: "Category",
      value: "New Patient",
    },
    {
      id: "evt-16",
      ts: 16,
      type: "click",
      url: EHR,
      selector: "button[name='form_save_appointment']",
      tagName: "BUTTON",
      text: "Save appointment",
    },
    {
      id: "evt-17",
      ts: 17,
      type: "click",
      url: EHR,
      selector: "a[href*='insurance']",
      tagName: "A",
      text: "Insurance (pencil)",
    },
    {
      id: "evt-18",
      ts: 18,
      type: "change",
      url: EHR,
      selector: "select[name='form_rel']",
      tagName: "SELECT",
      text: "Relationship",
      value: "Self",
    },
    {
      id: "evt-19",
      ts: 19,
      type: "input",
      url: EHR,
      selector: "input[name='form_policy']",
      tagName: "INPUT",
      text: "Policy / member number",
      value: "HACKDEMO-POL-1044",
    },
    {
      id: "evt-20",
      ts: 20,
      type: "click",
      url: EHR,
      selector: "button[name='form_save_policy']",
      tagName: "BUTTON",
      text: "Save Policy",
    },
    {
      id: "evt-21",
      ts: 21,
      type: "click",
      url: EHR,
      selector: "a[href*='documents']",
      tagName: "A",
      text: "Documents → Medical Record",
    },
    {
      id: "evt-22",
      ts: 22,
      type: "change",
      url: EHR,
      selector: "input[type='file']",
      tagName: "INPUT",
      text: "Upload the same referral PDF",
      value: "referral-fax.pdf",
    },
  ],
  steps: [
    {
      id: "step-inbox",
      title: "1. Open the referral PDF in email",
      action: "click",
      selector: "Inbox → referral thread → PDF attachment",
      url: INBOX,
      eventIds: ["evt-01", "evt-02", "evt-03"],
      notes:
        "Starts in Mary's inbox, not in the EHR. The PDF is the source of field values. Inbox DOM is gone once she leaves this tab.",
    },
    {
      id: "step-login",
      title: "2. Log into the EHR",
      action: "fill",
      selector: "#authUser",
      url: EHR,
      eventIds: ["evt-04", "evt-05", "evt-06", "evt-07"],
      notes: "Password is never stored (••••). Headed browser; she types it. Login screen is a different document than the four forms.",
    },
    {
      id: "step-screen-1",
      title: "3. Screen 1 — New patient",
      action: "fill",
      selector: "Patient > New/Search",
      url: EHR,
      eventIds: ["evt-08", "evt-09", "evt-10", "evt-11", "evt-12", "evt-13"],
      notes: "Map PDF fields onto first name, last name, DOB, sex. Confirm duplicate check. This tree did not exist until after login.",
    },
    {
      id: "step-screen-2",
      title: "4. Screen 2 — First visit",
      action: "click",
      selector: "Dashboard → Appointments +",
      url: EHR,
      eventIds: ["evt-14", "evt-15", "evt-16"],
      notes: "Category New Patient. OK “Provider not available, use it anyway?” Appointment UI hydrates only after the patient exists.",
    },
    {
      id: "step-screen-3",
      title: "5. Screen 3 — Insurance",
      action: "fill",
      selector: "Dashboard → Insurance",
      url: EHR,
      eventIds: ["evt-17", "evt-18", "evt-19", "evt-20"],
      notes: "Relationship Self first, then company, policy/member, group, dates, subscriber address from the PDF. Save Policy.",
    },
    {
      id: "step-screen-4",
      title: "6. Screen 4 — Attach the fax",
      action: "click",
      selector: "Documents → Medical Record",
      url: EHR,
      eventIds: ["evt-21", "evt-22"],
      notes: "Upload the same PDF from the email. File picker and documents frame were not in the patient form DOM.",
    },
  ],
};
